### PR TITLE
implemented progressbar

### PR DESCRIPTION
**Pull request by rsmuc**
implemented a progressbar for mailprocessing:

100%|###################################################################################################################################################################|
0 spams found in 50 messages
0/0 was automatically deleted

the progressbar will only be shown if there are mails to process and if --noninteractive is not set.

see issue #57

### CODE REVIEW

**Comment by baldurmen** [comment]
Hi! Thanks for the patch, but I'd rather not depend on an external dependency for such a small thing. Have you had a look at the code listed here? https://gist.github.com/aubricus/f91fb55dc6ba5557fbab06119420dd6a

The more deps we use, the harder ISBG gets to package in distros. A personal goal of mine would be to get ISBG packaged in Debian.

Happy to talk about this.

**Comment by rsmuc** [comment]
I tried that code snipped, but received some asci errors. And progressbar2 was working fine.
Maybe I'll check next week for another solution.

**Comment by rsmuc** [comment]
I found a nice solution without external dependencies.

**Comment by baldurmen** [comment]
Neat! I'll test that as soon as I can.

**Comment by rsmuc** [comment]
the progressbar seems to cause trouble, if isbg is executed via cron. I will check if I find a solution for that.

**Comment by rsmuc** [comment]
Currently i have no time to fix that. So i will close that pull request and will reopen it, when i have a fix

**Pull request closed without merging**
