### PR TITLE
Version bump to 1.01

### PR DESCRIPTION
**Pull request by baldurmen**
**PLEASE DO NOT MERGE THIS YET! I'M CURRENTLY TESTING IT IN PRODUCTION TO SEE IF IT'S FINE**

This is the version bump to 1.01. The code has been refactored to put all the loose code into defined functions.

The goal behind this is to make the code clearer to be eventually able to write a decent main().

It's quite a large pull, so it may create a few bugs if it's not tested correctly.

### CODE REVIEW

**Comment by dantefff** [comment]
I have found a bug in this pull request, the password is not saved (maybe it is not correctly retrieved or ignored)

**Comment by baldurmen** [comment]
@dantefff yeah, that's one of the features I do not use so I did not have to test it yet. Could you give me the full command (without the actual password used) and the error trace (if there is one?).

**Comment by dantefff** [comment]
@baldurmen not much to say, I was setting up isbg with your fork and if I pass the --savepw argument, it asks me for password and generates a .isbg-* file (to store the password). If I run isbg again without the --savepw it asks me again for password (it should use the stored password instead of asking it again).

**Comment by OzzieIsaacs** [comment]
To fix the issue of @dantefff you should implement a additional:

`if imappasswd is None:`

in line 384, so line 385 to 400 are only executed if the passwordfile can't be read. (This statement is in the original code at this line)

**Comment by baldurmen** [comment]
@dantefff see @OzzieIsaacs 's commit. Thanks a lot!

(still testing v1.01live right now, will merge when I'll be sure there are no other bugs. If you wish to test it too, you can use my personnal fork (I use it as a dev branch: https://github.com/baldurmen/isbg))

**Comment by dantefff** [comment]
Thanks a lot!

2016-06-18 21:16 GMT+02:00 Louis-Philippe Véronneau <
notifications@github.com>:

**Comment by baldurmen** [comment]
Doing some git refactoring here. I'm going to do proper branches for each pull, so consider this PR as closed for now (code is not lost!)

**Pull request closed without merging**
