### PR TITLE
Add --learnthenflag

### PR DESCRIPTION
**Pull request by duk3luk3**
Works analogously to `--learnthendestroy`

Needs a check to make sure `--learnthendestroy` and `--learnthenflag` are not used at the same time.

I'll fix that if there's interest to merge this.

### CODE REVIEW

**Comment by duk3luk3** [comment]
(The PR flag is now a grab bag of changes I found necessary for my own deployment of isbg; I'll probably eventually fork it and do the "modernisation" talked about it another PR. So this PR mostly exists as an exercise of "throwing stuff over the wall" now.)

**Comment by baldurmen** [comment]
Hey thanks for that. I'll look at this during the Christmas holidays and try to merge it.

**Comment by duk3luk3** [comment]
Great! It's now rebased for your please.

**Comment by duk3luk3** [comment]
I've started work on the "modernisation" now. Hopefully it'll be ready in time for a christmas present :-)

**Comment by baldurmen** [comment]
Feel free to create a new branch (2.0?) and to create another pull so I can help if I have some time!

**Comment by duk3luk3** [comment]
Will do. I have chosen to encapsulate the script in a python class with minimal changes in behaviour as a first step, when that is done I will open a PR.

**Comment by baldurmen** [comment]
All of the commits here are included in #63 already.

**Pull request closed without merging**
